import portfolioImg01 from "../../images/portfolio_img01.png";
import portfolioImg02 from "../../images/portfolio_img02.png";
import portfolioImg03 from "../../images/portfolio_img03.png";
import portfolioImg04 from "../../images/portfolio_img04.png";
import portfolioImg05 from "../../images/portfolio_img05.png";
import portfolioImg06 from "../../images/portfolio_img06.png";
import portfolioImg07 from "../../images/portfolio_img07.png";

export const portfolioArr = [
  {
    idx: 1,
    image: portfolioImg01,
    filterVal: ["web"],
    subTitle: "Web",
    title: "반응형 웹 포트폴리오",
    period: "2020.11 - 2021.01",
    ide: "VS Code",
    skill: "ReactJS / HTML / SCSS",
    join: "2",
    contents: [
      "✔ React, scss 스터디 겸 웹 포트폴리오 프로젝트",
      "✔ Github 무료 호스팅 사용",
      "https://baekdorazi.github.io/portfolio/",
    ],
    fontColor: "black", //배경색 어두운색일때 흰색으로 하고 아닐때 검정색으로 하기위해 추가
  },
  {
    idx: 2,
    image: portfolioImg02,
    filterVal: ["android", "web"],
    subTitle: "Android & Web",
    title: "KT GIGA 스마트팜(통합관제시스템)",
    period: "2018.06 - 2020.09",
    ide: "Android Studio / VS Code",
    skill: "ReactJS / HTML / SCSS / JAVA",
    join: "5",
    contents: [
      "✔ App 사용자 디바이스 등록, Notification",
      "　　CCTV 실시간 모니터링 기능 개발",
      "✔ Web 실시간 모니터링, 이벤트 영상조회,",
      "　　영농일지 관련 화면, 페로몬 트랩화면 개발(React)",
      "✔ RESTFul API 사용",
    ],
    fontColor: "black",
  },
  // {
  //   idx: 3,
  //   image: portfolioImg03,
  //   filterVal: ["android", "web"],
  //   subTitle: "Android & Web",
  //   title: "Supervisor(ARGOS RPA+)",
  //   period: "2019.05 - 2019.07",
  //   ide: "Android Studio / VS Code",
  //   join: "6",
  //   contents: [
  //     "✔ 알림 설정 화면, On-demand 화면 개발(Vue)",
  //     "✔ Google Play Store 등록",
  //     "https://play.google.com/store/apps/details?id=com.alabs.rpa.chief"
  //   ],
  //   fontColor: "black",
  // },
  {
    idx: 4,
    image: portfolioImg04,
    filterVal: ["android"],
    subTitle: "Android",
    title: "HUDVoca",
    period: "2019.09 - 2019.11",
    ide: "Android Studio",
    skill: "JAVA",
    join: "2",
    contents: [
      "✔ Head Up Display Vocabulary",
      "✔ 차량 앞 유리창에 반사하여 영어단어 공부하는 Application",
      "✔ 5초, 30초, 1분, 5분 시간 설정하면",
      "ㅤㅤ시간마다 영어단어가 변경되며 화면에 보임",
      "✔ 일반모드, 차량모드 지원",
      "✔ Google Play Store 등록",
      "https://play.google.com/store/apps/details?id=com.baekzombie.hudvoca",
    ],
    fontColor: "black",
  },
  {
    idx: 5,
    image: portfolioImg05,
    filterVal: ["android"],
    subTitle: "Android",
    title: "KT 농산물 이력정보 제공 서비스",
    period: "2018.01 - 2018.04",
    ide: "Android Studio",
    skill: "JAVA",
    join: "4",
    contents: [
      "✔ 도매유통 디지털화 Application",
      "✔ 각 사용자 계정(APC, 하역업체,",
      "　　도매법인, 중도매인)에 맞는 메뉴 UI 지원",
      "✔ 바코드 스캔 기능",
      "✔ 전자문서 작성 및 관리 기능(전자송품장, 주문표 등)",
    ],
    fontColor: "black",
  },
  {
    idx: 6,
    image: portfolioImg06,
    filterVal: ["android"],
    subTitle: "Android",
    title: "GPOP(Global POP)",
    period: "2016.11 - 2017.01",
    ide: "ADT(Eclipse)",
    skill: "JAVA",
    join: "3",
    contents: [
      "✔ 현재 연결된 네트워크 속도 측정 Application",
      "✔ 현재 네트워크의 Ping, Upload,",
      "ㅤㅤDownload 속도 측정 및 결과 조회",
      "✔ Trace Route 측정 및 측정 결과 조회",
    ],
    fontColor: "white",
  },
  {
    idx: 7,
    image: portfolioImg07,
    filterVal: ["android"],
    subTitle: "Android",
    title: "Go!Dutch",
    period: "2016.03 - 2016.03",
    ide: "Android Studio",
    skill: "JAVA",
    join: "1",
    contents: [
      "✔ 가격과 인원수를 입력하여",
      "　　1인 송금액을 계산해 주는 App",
      "✔ 더치페이 된 금액, 은행명, 계좌번호를",
      "　　카카오톡으로 전송 가능",
      "✔ Firebase  Admob 라이브러리 사용(광고)",
      "✔ Kakao SDK 사용",
      "✔ 전체 리디자인(2020.01)",
      "✔ Google Play Store 등록",
      "https://play.google.com/store/apps/details?id=com.baek.dutchpay",
    ],
    fontColor: "white",
  },
  // {
  //   idx: 8,
  //   image: portfolioTest,
  //   filterVal: ["android"],
  //   subTitle: "Andriod",
  //   title: "Travel Diary",
  //   period: "2015.09 - 2015.09",
  //   ide: "ADT(Eclipse)",
  //   join: "1",
  //   contents: [
  //     "✔ 여행을 다니며 사진을 찍고, 추억을 실시간으로 기록하는 Application",
  //     "✔ SQLite 사용하여 데이터 저장",
  //     "✔ 등록된 여행 날짜의 1년 뒤 같은 날짜에 푸시 알림으로 표시",
  //     "✔ 글 메모, 카메라 메모 기능",
  //     "✔ 메모 기능의 글자 속성 변경 기능",
  //   ],
  //   fontColor: "black",
  // },
  // {
  //   idx: 9,
  //   image: portfolioTest,
  //   filterVal: ["android"],
  //   subTitle: "Android",
  //   title: "Nice Timer",
  //   period: "2015.05 - 2015.05",
  //   ide: "ADT(Eclipse)",
  //   join: "1",
  //   contents: [
  //     "✔ 공부 및 낮잠, 시간 개념이 없는 사람을 위한 Application",
  //     "✔ 시, 분을 입력 후 타이머가 울릴 타입(진동, 소리) 선택",
  //     "✔ 저장 후 타이머 울릴 시간 표시",
  //     "✔ 수학 연산 정답 확인을 통한 알림 중지",
  //   ],
  //   fontColor: "black",
  // },
];
